//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> OpId { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
    
        public virtual Operations Operations { get; set; }
    }
}
